### ISSUE TITLE
:unneeded is disabled

### ISSUE THREAD

**Issue by murphy2712** [nesium/homebrew-tools#1]
I'm having this error when trying to install xcode-color-assets:

Error: nesium/tools/xcode-color-assets: Calling bottle :unneeded is disabled! There is no replacement.
Please report this issue to the nesium/tools tap (not Homebrew/brew or Homebrew/core):
  /opt/homebrew/Library/Taps/nesium/homebrew-tools/xcode-color-assets.rb:7

Using Homebrew 3.4.1

**Comment by nesium** [comment]
Hi @murphy2712. I've removed the `bottle :unneeded`. Installation should be working as expected again.

**Comment by murphy2712** [comment]
Thanks!
