### ISSUE TITLE
xcode-color-assets doesn't run natively on Apple silicon

### ISSUE THREAD

**Issue by herrernst** [nesium/homebrew-tools#2]
Hi, first of all, thank you for your work and providing it as open source.
But when trying to run xcode-color-assets on my new M2 Mac, I get `bad CPU type in executable: xcode-color-assets`

Trying manually verifies there's no arm64 binary:
```
% curl -sOL https://github.com/nesium/xcode-color-assets/releases/download/0.6.0/xcode-color-assets-0.6.0.tar.gz
% tar xzf xcode-color-assets-0.6.0.tar.gz 
% file xcode-color-assets
xcode-color-assets: Mach-O 64-bit executable x86_64
```
Would you mind rebuilding for both architectures? Thank you!

**Comment by nesium** [comment]
Hi @herrernst. I've uploaded a new release that contains a universal binary.

**Comment by herrernst** [comment]
Thank you, it's working!
